### ISSUE TITLE
Any chance to support `ORDER BY` statement?

### ISSUE THREAD

**Issue by weeee9** [VauntDev/tqla#25]
Any chance to support `ORDER BY` statement? so we don't have to do things like
```go
tmpl := "SELECT * FROM t1 WHERE username = {{ . }} ORDER BY %s %s;

tmpl = fmt.Sprintf(tmpl, "id", "ASC")

...

tqla.Compile(tmpl, "abc")
```

**Comment by elewis787** [comment]
I added a test to show how you could accomplish order by 

https://github.com/VauntDev/tqla/pull/26 

Using a custom function would be the ideal solution but doing so could open up to SQL injection. 

One thought I have had would be to create a set of supported functions ( i.e orderBy ) that are treated uniquely - this would return a string value instead of an escaped argument ( order by column vs $1 etc..  )  

Let me know if this helps - I'll explore the special functions route again but I have avoided it in the past. 

Another option would be to use numeric values for the order by statement if you know the index. That would simplify the example a little bit.

**Comment by elewis787** [comment]
I am closing this since it is doable. However, this is related to #17 and we can track a more user-friendly/long solution there.
